version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "21 2 12 * *"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 15
    assignees:
      - "Bannsaenger"
    versioning-strategy: increase

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "21 2 12 * *"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 15
    assignees:
      - "Bannsaenger"
